### ISSUE TITLE
Create a Job view in FE

### ISSUE THREAD

**Issue by kshpdr** [kshpdr/scalable-systems#16]
**Task description**
We want to introduce new form with job input and then a graph according to already existing clusters (similar to scheduling).

Job form should have:
- name - string
- deadline - date (optional)
- stoppable - boolean (where a job can be stopped)
- time - int (in seconds)

**Comment by Julius-crt** [comment]
(the json object returned from backend will look like this:)

- name - string
- deadline - date (optional)
- stoppable - boolean (where a job can be stopped)
- time - int (in seconds)
- computetime - int (in seconds)
- regionname - String
- timewindow[] - Datetime

**Comment by kshpdr** [comment]
Project ended.
