### ISSUE TITLE
Add an external API call to the server

### ISSUE THREAD

**Issue by kshpdr** [kshpdr/scalable-systems#8]
**Task description**
We want to give a response of the best location for a cluster using real data. 
As a first step we want to add an API call to https://carbon-intensity.github.io/api-definitions/#get-regional in our server so that we can take the best region.

**Tasks**
- Add into server an API call to get-regional and display result in the CLI

**Comment by Julius-crt** [comment]
Java script sucks, i implemented an external api call but the code is not well writen. At least one gets the cleanest region as a JSON object. When calling localhost:3001/api/externalApi. 
Might refactor, when i got time

**Comment by kshpdr** [comment]
Project ended.
